version: "3.9"
services: 
  server:
    image: node
    command: sh -c "npm install && npm run watch"
    ports: 
      - 3000:3000
    working_dir: /app
    volumes: 
      - ./server:/app
    environment: 
      JWT: 26C36D6D18F7267E5C6A88747A61C
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: twitter
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
      
  db:
    image: postgres
    volumes: 
      - postgres-db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: twitter
      
  client:
    image: node
    command: sh -c "npm install && npm start"
    ports: 
      - 8000:3000
    working_dir: /app
    volumes: 
      - ./client:/app
    stdin_open: true

volumes: 
  postgres-db: